### PR TITLE
vdk-jupyter: run tests in CI 

### PR DESCRIPTION
**Pull request by murphp15**
# Why? 
We need to run jupyter tests in CICD to make sure there are no failures/regressions. 

Please note i have commented out failing tests: https://github.com/vmware/versatile-data-kit/issues/2870

# How has this been tested? 

Passing now. 
In this PR I tested failures are reported as expected https://github.com/vmware/versatile-data-kit/pull/2872

### CODE REVIEW

**Review by yonitoo — APPROVED** [review]
LGTM! What turned out to be the problem after all? I see we use a different image now. Was that it?

**Comment by murphp15** [comment]
@yonitoo 
I'm not exactly sure what was causing the issue. I just went through every step and removed anything that wasn't totally necessary and then it started working.

**Comment by duyguHsnHsn** [comment]
I see that 3 jobs are skipped do we know the reason why? 
Screenshot 2023-11-03 at 12 57 40

**Comment by murphp15** [comment]
@duyguHsnHsn yeah I will fix that in a separate pr. I have the fix locally

**Comment by duyguHsnHsn** [comment]
@paul-dimitrov how do we get alerted for those?

**Comment by murphp15** [comment]
@duyguHsnHsn the gitlab job will be marked as a fail and it will be handle as normal?

**Review by duyguHsnHsn — APPROVED** [review]

**Pull request merged**
