### PR TITLE
Person/murphp15/shared component docs minus vep

### PR DESCRIPTION
**Pull request by murphp15**
# What
We want to do preliminary work on setting up folder structure/docs etc for the frontend code. 
**The VEP will be included in a separate PR**

# Why 
It will be a first step in closing this https://github.com/vmware/versatile-data-kit/issues/1507. 

# How has this been tested 
No testing necessary  

- [x] add .gitignore, and initially empty .gitlab-ci/ dir
- [x]  remove .reviewboardrc and all from support/* -> except eventually keep open_docker.ps1
- [x]  we should keep the CHANGELOG.md, rename header, and move it and version.txt to 3.0.0 (keep the all exact entries including @vmw-prefixed as well)
- [x] cleanup the CHANGELOG.md (in OSS, changelog is dynamically generated)
- [x] move projects/gui/version.txt to 3.0.0
- [x] cleanup README.md from internal information
- [x] rework the .md documentation to workaround internal links, instead link to the VEP and make sure to transfer any needed information there. 
- [x] projects/gui/proxy.config.jsonrequires a data pipelines control service instance for e2e testing -> reuse http://cicd-control-service-svc:8092/ k8s-internal domain like the vdk-heartbeat
- [x] cleanup metadata service entries
- [x] keep http://localhost.vmware.com:4200/
- [x] Take a look what directories to keep, needed for old @taurus/data-pipelines:[^taurus_shared_open_source_plan.txt], a part of the research story https://jira.eng.vmware.com/browse/SC-1656
- [x] e2e tests are not data-pipelines -related, so all e2e/ dir content is descoped

Signed-off-by: murphp15 <murphp15@tcd.ie>

### CODE REVIEW

**Comment by murphp15** [comment]
@ivakoleva  do you want the folder to be shared or shared-components?

**Comment by sabadzhiev** [comment]
@murphp15 One comment on the naming of the 'projects/frontend-ui'. frontend-ui sounds like a tautology. 
I guess just 'projects/frontend' sounds better.

**Comment by sabadzhiev** [comment]
I would propose a few more naming/restructuring changes: 
#1: Remove the folder projects/frontend-ui/shared/projects/gui/projects/shared I believe the code for the shared component should be in: projects/frontend-ui/shared/projects/gui

#2: projects/frontend-ui/**_shared_**/projects/**_gui_** to become -> projects/frontend-ui/**_shared-components_**/projects/**_shared_**

**Comment by ivakoleva** [comment]
> @ivakoleva do you want the folder to be shared or shared-components?

Directories structure and naming should be reflecting the Frontend proposal VEP specification, that actually explains what the purpose of the directory is.
Having the VEP first, provides public information on what the proposal is. Then creating a directory according the VEP is like 2 minutes of work, and the PR would not be blocked after the topic had already been resolved in the VEP specification, where the discussion is tracked.

**Pull request closed without merging**
