### PR TITLE
vdk-oracle: remove secrets override

### PR DESCRIPTION
**Pull request by duyguHsnHsn**
Solving: https://github.com/vmware/versatile-data-kit/issues/3156 

Tested: locally with job runs

Signed-off-by: Duygu Hasan [hduygu@vmware.com](mailto:hduygu@vmware.com)

### CODE REVIEW

**Comment by murphp15** [comment]
have you tested it? 
Looks good

**Comment by duyguHsnHsn** [comment]
> have you tested it? Looks good

Yes, I have tested it, I will add a comment about it now

**Comment by murphp15** [comment]
does locally running jobs use secrets?

**Comment by duyguHsnHsn** [comment]
I have tested it with SC

**Review by murphp15 — APPROVED** [review]

**Review by DeltaMichael — APPROVED** [review]

**Pull request merged**
