### PR TITLE
control-service: fix job monitoring

### PR DESCRIPTION
**Pull request by mivanov1988**
At the moment, after the control service is being redeployed,
all K8s jobs and K8s PODs to them are retrieved in order to
synchronize potentially missed K8s events.
Usually, the process synchronizes the K8s Jobs for the last few minutes
but in case of redeploy it synchronizes all jobs
as the variable `lastWatchTime`=0.

This change sets the appropriate `lastWatchTime` default value, 
thus reducing the synchronization time.

Testing Done: unit tests

Signed-off-by: Miroslav Ivanov miroslavi@vmware.com

### CODE REVIEW

**Comment by tozka** [comment]
So if the control service is down for 1 hour, it is going to miss the first half an hour of events?

**Comment by ivakoleva** [comment]
Sounds like a persistent dynamic value to me

**Comment by tpalashki** [comment]
`` is something that we can persist

**Comment by tpalashki** [comment]
Closed by mistake. Apologies.

**Comment by mivanov1988** [comment]
> So if the control service is down for 1 hour, it is going to miss the first half an hour of events?

Yes, that's correct, but it is temporary solution. We can use DB column `shedlock.locked_at` as a default value.

**Review by tpalashki — APPROVED** [review]
I agree with what others say, but I think that this change will solve more problems than it would cause until we implement a more sophisticated solution. I don't believe we had a case with the service down for 30+ minutes. On the other hand, there is a delay during every deployment, which could cause issues.

**Pull request merged**
