### PR TITLE
vdk-kerberos-auth: provide variable to specify krb5.conf configuration

### PR DESCRIPTION
**Pull request by tpalashki**
Currently, the Kerberos authentication is always using a generic
krb5.conf file built into the plugin. This commits enables specifying
the path to the krb5.conf file via configuration (`KRB5_CONF_FILENAME`).
If the configuration is not set, it defaults to the built-in file.

Testing done: manually running the `run` command with and without the
new configuration and observing that the appropriate krb5.conf file is
being used.

Signed-off-by: Tsvetomir Palashki <tpalashki@vmware.com>

### CODE REVIEW

**Review by ivakoleva — COMMENTED** [review]
Looking at the description, and Testing Done section specifically, I think adding test coverage to verify the configurations are being set as expected, is a trivial task to do; Of course, the need for this would be obsolete, when we come up with functional tests to check entire operability, that are missing presently

**Comment by ivakoleva** [comment]
Have you considered something like https://hub.docker.com/r/openmicroscopy/apacheds ?

**Comment by tpalashki** [comment]
I am currently looking at https://hub.docker.com/r/gcavalcante8808/krb5-server/ and exploring if I can use it to functionally test the entire plugin.

**Comment by mivanov1988** [comment]
LGTM

**Review by ivakoleva — APPROVED** [review]
Maybe create another PR with tests with a docker image running?

**Comment by tpalashki** [comment]
> Maybe create another PR with tests with a docker image running?

Thank you, I will.

**Pull request merged**
